// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: realm/v1/admin.proto

package realmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminRBACService_ListAdmins_FullMethodName             = "/realm.v1.AdminRBACService/ListAdmins"
	AdminRBACService_AddAdmin_FullMethodName               = "/realm.v1.AdminRBACService/AddAdmin"
	AdminRBACService_UpdateAdminPermissions_FullMethodName = "/realm.v1.AdminRBACService/UpdateAdminPermissions"
	AdminRBACService_RemoveAdmin_FullMethodName            = "/realm.v1.AdminRBACService/RemoveAdmin"
)

// AdminRBACServiceClient is the client API for AdminRBACService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminRBACServiceClient interface {
	ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error)
	AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AdminUser, error)
	UpdateAdminPermissions(ctx context.Context, in *UpdateAdminPermissionsRequest, opts ...grpc.CallOption) (*AdminUser, error)
	RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error)
}

type adminRBACServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRBACServiceClient(cc grpc.ClientConnInterface) AdminRBACServiceClient {
	return &adminRBACServiceClient{cc}
}

func (c *adminRBACServiceClient) ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminsResponse)
	err := c.cc.Invoke(ctx, AdminRBACService_ListAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRBACServiceClient) AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AdminUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUser)
	err := c.cc.Invoke(ctx, AdminRBACService_AddAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRBACServiceClient) UpdateAdminPermissions(ctx context.Context, in *UpdateAdminPermissionsRequest, opts ...grpc.CallOption) (*AdminUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUser)
	err := c.cc.Invoke(ctx, AdminRBACService_UpdateAdminPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRBACServiceClient) RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*AdminOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOperationResponse)
	err := c.cc.Invoke(ctx, AdminRBACService_RemoveAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRBACServiceServer is the server API for AdminRBACService service.
// All implementations must embed UnimplementedAdminRBACServiceServer
// for forward compatibility.
type AdminRBACServiceServer interface {
	ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error)
	AddAdmin(context.Context, *AddAdminRequest) (*AdminUser, error)
	UpdateAdminPermissions(context.Context, *UpdateAdminPermissionsRequest) (*AdminUser, error)
	RemoveAdmin(context.Context, *RemoveAdminRequest) (*AdminOperationResponse, error)
	mustEmbedUnimplementedAdminRBACServiceServer()
}

// UnimplementedAdminRBACServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminRBACServiceServer struct{}

func (UnimplementedAdminRBACServiceServer) ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdmins not implemented")
}
func (UnimplementedAdminRBACServiceServer) AddAdmin(context.Context, *AddAdminRequest) (*AdminUser, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdmin not implemented")
}
func (UnimplementedAdminRBACServiceServer) UpdateAdminPermissions(context.Context, *UpdateAdminPermissionsRequest) (*AdminUser, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdminPermissions not implemented")
}
func (UnimplementedAdminRBACServiceServer) RemoveAdmin(context.Context, *RemoveAdminRequest) (*AdminOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAdmin not implemented")
}
func (UnimplementedAdminRBACServiceServer) mustEmbedUnimplementedAdminRBACServiceServer() {}
func (UnimplementedAdminRBACServiceServer) testEmbeddedByValue()                          {}

// UnsafeAdminRBACServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRBACServiceServer will
// result in compilation errors.
type UnsafeAdminRBACServiceServer interface {
	mustEmbedUnimplementedAdminRBACServiceServer()
}

func RegisterAdminRBACServiceServer(s grpc.ServiceRegistrar, srv AdminRBACServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminRBACServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminRBACService_ServiceDesc, srv)
}

func _AdminRBACService_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRBACServiceServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRBACService_ListAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRBACServiceServer).ListAdmins(ctx, req.(*ListAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRBACService_AddAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRBACServiceServer).AddAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRBACService_AddAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRBACServiceServer).AddAdmin(ctx, req.(*AddAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRBACService_UpdateAdminPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRBACServiceServer).UpdateAdminPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRBACService_UpdateAdminPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRBACServiceServer).UpdateAdminPermissions(ctx, req.(*UpdateAdminPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRBACService_RemoveAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRBACServiceServer).RemoveAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRBACService_RemoveAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRBACServiceServer).RemoveAdmin(ctx, req.(*RemoveAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRBACService_ServiceDesc is the grpc.ServiceDesc for AdminRBACService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRBACService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realm.v1.AdminRBACService",
	HandlerType: (*AdminRBACServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAdmins",
			Handler:    _AdminRBACService_ListAdmins_Handler,
		},
		{
			MethodName: "AddAdmin",
			Handler:    _AdminRBACService_AddAdmin_Handler,
		},
		{
			MethodName: "UpdateAdminPermissions",
			Handler:    _AdminRBACService_UpdateAdminPermissions_Handler,
		},
		{
			MethodName: "RemoveAdmin",
			Handler:    _AdminRBACService_RemoveAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "realm/v1/admin.proto",
}
