// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: realm/v1/admin.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	IsSuperadmin  bool                   `protobuf:"varint,3,opt,name=is_superadmin,json=isSuperadmin,proto3" json:"is_superadmin,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_realm_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AdminUser) GetIsSuperadmin() bool {
	if x != nil {
		return x.IsSuperadmin
	}
	return false
}

func (x *AdminUser) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminUser) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRequest) Reset() {
	*x = ListAdminsRequest{}
	mi := &file_realm_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRequest) ProtoMessage() {}

func (x *ListAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ListAdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminUser           `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsResponse) Reset() {
	*x = ListAdminsResponse{}
	mi := &file_realm_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsResponse) ProtoMessage() {}

func (x *ListAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminsResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListAdminsResponse) GetAdmins() []*AdminUser {
	if x != nil {
		return x.Admins
	}
	return nil
}

type AddAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminRequest) Reset() {
	*x = AddAdminRequest{}
	mi := &file_realm_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminRequest) ProtoMessage() {}

func (x *AddAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminRequest.ProtoReflect.Descriptor instead.
func (*AddAdminRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AddAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddAdminRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateAdminPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminPermissionsRequest) Reset() {
	*x = UpdateAdminPermissionsRequest{}
	mi := &file_realm_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminPermissionsRequest) ProtoMessage() {}

func (x *UpdateAdminPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminPermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAdminPermissionsRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *UpdateAdminPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RemoveAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminRequest) Reset() {
	*x = RemoveAdminRequest{}
	mi := &file_realm_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminRequest) ProtoMessage() {}

func (x *RemoveAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminRequest.ProtoReflect.Descriptor instead.
func (*RemoveAdminRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAdminRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type AdminOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminOperationResponse) Reset() {
	*x = AdminOperationResponse{}
	mi := &file_realm_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOperationResponse) ProtoMessage() {}

func (x *AdminOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOperationResponse.ProtoReflect.Descriptor instead.
func (*AdminOperationResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminOperationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_realm_v1_admin_proto protoreflect.FileDescriptor

const file_realm_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14realm/v1/admin.proto\x12\brealm.v1\x1a\x13realm/v1/auth.proto\"\xc4\x01\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.realm.v1.UserR\x04user\x12#\n" +
	"\ris_superadmin\x18\x03 \x01(\bR\fisSuperadmin\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x13\n" +
	"\x11ListAdminsRequest\"A\n" +
	"\x12ListAdminsResponse\x12+\n" +
	"\x06admins\x18\x01 \x03(\v2\x13.realm.v1.AdminUserR\x06admins\"I\n" +
	"\x0fAddAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\\\n" +
	"\x1dUpdateAdminPermissionsRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"/\n" +
	"\x12RemoveAdminRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\"J\n" +
	"\x16AdminOperationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbe\x02\n" +
	"\x10AdminRBACService\x12G\n" +
	"\n" +
	"ListAdmins\x12\x1b.realm.v1.ListAdminsRequest\x1a\x1c.realm.v1.ListAdminsResponse\x12:\n" +
	"\bAddAdmin\x12\x19.realm.v1.AddAdminRequest\x1a\x13.realm.v1.AdminUser\x12V\n" +
	"\x16UpdateAdminPermissions\x12'.realm.v1.UpdateAdminPermissionsRequest\x1a\x13.realm.v1.AdminUser\x12M\n" +
	"\vRemoveAdmin\x12\x1c.realm.v1.RemoveAdminRequest\x1a .realm.v1.AdminOperationResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_realm_v1_admin_proto_rawDescOnce sync.Once
	file_realm_v1_admin_proto_rawDescData []byte
)

func file_realm_v1_admin_proto_rawDescGZIP() []byte {
	file_realm_v1_admin_proto_rawDescOnce.Do(func() {
		file_realm_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realm_v1_admin_proto_rawDesc), len(file_realm_v1_admin_proto_rawDesc)))
	})
	return file_realm_v1_admin_proto_rawDescData
}

var file_realm_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_realm_v1_admin_proto_goTypes = []any{
	(*AdminUser)(nil),                     // 0: realm.v1.AdminUser
	(*ListAdminsRequest)(nil),             // 1: realm.v1.ListAdminsRequest
	(*ListAdminsResponse)(nil),            // 2: realm.v1.ListAdminsResponse
	(*AddAdminRequest)(nil),               // 3: realm.v1.AddAdminRequest
	(*UpdateAdminPermissionsRequest)(nil), // 4: realm.v1.UpdateAdminPermissionsRequest
	(*RemoveAdminRequest)(nil),            // 5: realm.v1.RemoveAdminRequest
	(*AdminOperationResponse)(nil),        // 6: realm.v1.AdminOperationResponse
	(*User)(nil),                          // 7: realm.v1.User
}
var file_realm_v1_admin_proto_depIdxs = []int32{
	7, // 0: realm.v1.AdminUser.user:type_name -> realm.v1.User
	0, // 1: realm.v1.ListAdminsResponse.admins:type_name -> realm.v1.AdminUser
	1, // 2: realm.v1.AdminRBACService.ListAdmins:input_type -> realm.v1.ListAdminsRequest
	3, // 3: realm.v1.AdminRBACService.AddAdmin:input_type -> realm.v1.AddAdminRequest
	4, // 4: realm.v1.AdminRBACService.UpdateAdminPermissions:input_type -> realm.v1.UpdateAdminPermissionsRequest
	5, // 5: realm.v1.AdminRBACService.RemoveAdmin:input_type -> realm.v1.RemoveAdminRequest
	2, // 6: realm.v1.AdminRBACService.ListAdmins:output_type -> realm.v1.ListAdminsResponse
	0, // 7: realm.v1.AdminRBACService.AddAdmin:output_type -> realm.v1.AdminUser
	0, // 8: realm.v1.AdminRBACService.UpdateAdminPermissions:output_type -> realm.v1.AdminUser
	6, // 9: realm.v1.AdminRBACService.RemoveAdmin:output_type -> realm.v1.AdminOperationResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_realm_v1_admin_proto_init() }
func file_realm_v1_admin_proto_init() {
	if File_realm_v1_admin_proto != nil {
		return
	}
	file_realm_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realm_v1_admin_proto_rawDesc), len(file_realm_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realm_v1_admin_proto_goTypes,
		DependencyIndexes: file_realm_v1_admin_proto_depIdxs,
		MessageInfos:      file_realm_v1_admin_proto_msgTypes,
	}.Build()
	File_realm_v1_admin_proto = out.File
	file_realm_v1_admin_proto_goTypes = nil
	file_realm_v1_admin_proto_depIdxs = nil
}
