// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/realm/v1/auth.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OAuthAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthAccount) Reset() {
	*x = OAuthAccount{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthAccount) ProtoMessage() {}

func (x *OAuthAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthAccount.ProtoReflect.Descriptor instead.
func (*OAuthAccount) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthAccount) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthAccount) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *OAuthAccount) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *OAuthAccount) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email              string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username           string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FullName           string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl          *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Provider           string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ConnectedAccounts  []*OAuthAccount        `protobuf:"bytes,9,rep,name=connected_accounts,json=connectedAccounts,proto3" json:"connected_accounts,omitempty"`
	HasPassword        bool                   `protobuf:"varint,10,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	ConnectedProviders []string               `protobuf:"bytes,11,rep,name=connected_providers,json=connectedProviders,proto3" json:"connected_providers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *User) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetConnectedAccounts() []*OAuthAccount {
	if x != nil {
		return x.ConnectedAccounts
	}
	return nil
}

func (x *User) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *User) GetConnectedProviders() []string {
	if x != nil {
		return x.ConnectedProviders
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{5}
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProfileResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      *string                `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type SetPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword *string                `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3,oneof" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetPasswordRequest) Reset() {
	*x = SetPasswordRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordRequest) ProtoMessage() {}

func (x *SetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SetPasswordRequest) GetCurrentPassword() string {
	if x != nil && x.CurrentPassword != nil {
		return *x.CurrentPassword
	}
	return ""
}

func (x *SetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type SetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordResponse) Reset() {
	*x = SetPasswordResponse{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordResponse) ProtoMessage() {}

func (x *SetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SetPasswordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CheckAvailabilityRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type CheckAvailabilityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UsernameAvailable *bool                  `protobuf:"varint,1,opt,name=username_available,json=usernameAvailable,proto3,oneof" json:"username_available,omitempty"`
	UsernameReason    *string                `protobuf:"bytes,2,opt,name=username_reason,json=usernameReason,proto3,oneof" json:"username_reason,omitempty"`
	EmailAvailable    *bool                  `protobuf:"varint,3,opt,name=email_available,json=emailAvailable,proto3,oneof" json:"email_available,omitempty"`
	EmailReason       *string                `protobuf:"bytes,4,opt,name=email_reason,json=emailReason,proto3,oneof" json:"email_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAvailabilityResponse) GetUsernameAvailable() bool {
	if x != nil && x.UsernameAvailable != nil {
		return *x.UsernameAvailable
	}
	return false
}

func (x *CheckAvailabilityResponse) GetUsernameReason() string {
	if x != nil && x.UsernameReason != nil {
		return *x.UsernameReason
	}
	return ""
}

func (x *CheckAvailabilityResponse) GetEmailAvailable() bool {
	if x != nil && x.EmailAvailable != nil {
		return *x.EmailAvailable
	}
	return false
}

func (x *CheckAvailabilityResponse) GetEmailReason() string {
	if x != nil && x.EmailReason != nil {
		return *x.EmailReason
	}
	return ""
}

type UnlinkOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkOAuthRequest) Reset() {
	*x = UnlinkOAuthRequest{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkOAuthRequest) ProtoMessage() {}

func (x *UnlinkOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkOAuthRequest.ProtoReflect.Descriptor instead.
func (*UnlinkOAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *UnlinkOAuthRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type UnlinkOAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkOAuthResponse) Reset() {
	*x = UnlinkOAuthResponse{}
	mi := &file_proto_realm_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkOAuthResponse) ProtoMessage() {}

func (x *UnlinkOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkOAuthResponse.ProtoReflect.Descriptor instead.
func (*UnlinkOAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UnlinkOAuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnlinkOAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_realm_v1_auth_proto protoreflect.FileDescriptor

const file_proto_realm_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19proto/realm/v1/auth.proto\x12\brealm.v1\"\xa1\x01\n" +
	"\fOAuthAccount\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB\b\n" +
	"\x06_emailB\r\n" +
	"\v_avatar_url\"\x8d\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12E\n" +
	"\x12connected_accounts\x18\t \x03(\v2\x16.realm.v1.OAuthAccountR\x11connectedAccounts\x12!\n" +
	"\fhas_password\x18\n" +
	" \x01(\bR\vhasPassword\x12/\n" +
	"\x13connected_providers\x18\v \x03(\tR\x12connectedProvidersB\r\n" +
	"\v_avatar_url\"\xaf\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"J\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"z\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\"\n" +
	"\x04user\x18\x04 \x01(\v2\x0e.realm.v1.UserR\x04user\"\x13\n" +
	"\x11GetProfileRequest\"x\n" +
	"\x0fProfileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\x0e.realm.v1.UserR\x04userB\n" +
	"\n" +
	"\b_message\"\xa7\x01\n" +
	"\x14UpdateProfileRequest\x12 \n" +
	"\tfull_name\x18\x01 \x01(\tH\x00R\bfullName\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x01R\busername\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tH\x02R\tavatarUrl\x88\x01\x01B\f\n" +
	"\n" +
	"_full_nameB\v\n" +
	"\t_usernameB\r\n" +
	"\v_avatar_url\"|\n" +
	"\x12SetPasswordRequest\x12.\n" +
	"\x10current_password\x18\x01 \x01(\tH\x00R\x0fcurrentPassword\x88\x01\x01\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPasswordB\x13\n" +
	"\x11_current_password\"G\n" +
	"\x13SetPasswordResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"m\n" +
	"\x18CheckAvailabilityRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_email\"\xa3\x02\n" +
	"\x19CheckAvailabilityResponse\x122\n" +
	"\x12username_available\x18\x01 \x01(\bH\x00R\x11usernameAvailable\x88\x01\x01\x12,\n" +
	"\x0fusername_reason\x18\x02 \x01(\tH\x01R\x0eusernameReason\x88\x01\x01\x12,\n" +
	"\x0femail_available\x18\x03 \x01(\bH\x02R\x0eemailAvailable\x88\x01\x01\x12&\n" +
	"\femail_reason\x18\x04 \x01(\tH\x03R\vemailReason\x88\x01\x01B\x15\n" +
	"\x13_username_availableB\x12\n" +
	"\x10_username_reasonB\x12\n" +
	"\x10_email_availableB\x0f\n" +
	"\r_email_reason\"0\n" +
	"\x12UnlinkOAuthRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"G\n" +
	"\x13UnlinkOAuthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8d\x04\n" +
	"\vAuthService\x12=\n" +
	"\bRegister\x12\x19.realm.v1.RegisterRequest\x1a\x16.realm.v1.AuthResponse\x127\n" +
	"\x05Login\x12\x16.realm.v1.LoginRequest\x1a\x16.realm.v1.AuthResponse\x12D\n" +
	"\n" +
	"GetProfile\x12\x1b.realm.v1.GetProfileRequest\x1a\x19.realm.v1.ProfileResponse\x12J\n" +
	"\rUpdateProfile\x12\x1e.realm.v1.UpdateProfileRequest\x1a\x19.realm.v1.ProfileResponse\x12J\n" +
	"\vSetPassword\x12\x1c.realm.v1.SetPasswordRequest\x1a\x1d.realm.v1.SetPasswordResponse\x12\\\n" +
	"\x11CheckAvailability\x12\".realm.v1.CheckAvailabilityRequest\x1a#.realm.v1.CheckAvailabilityResponse\x12J\n" +
	"\vUnlinkOAuth\x12\x1c.realm.v1.UnlinkOAuthRequest\x1a\x1d.realm.v1.UnlinkOAuthResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_proto_realm_v1_auth_proto_rawDescOnce sync.Once
	file_proto_realm_v1_auth_proto_rawDescData []byte
)

func file_proto_realm_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_realm_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_realm_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realm_v1_auth_proto_rawDesc), len(file_proto_realm_v1_auth_proto_rawDesc)))
	})
	return file_proto_realm_v1_auth_proto_rawDescData
}

var file_proto_realm_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_realm_v1_auth_proto_goTypes = []any{
	(*OAuthAccount)(nil),              // 0: realm.v1.OAuthAccount
	(*User)(nil),                      // 1: realm.v1.User
	(*RegisterRequest)(nil),           // 2: realm.v1.RegisterRequest
	(*LoginRequest)(nil),              // 3: realm.v1.LoginRequest
	(*AuthResponse)(nil),              // 4: realm.v1.AuthResponse
	(*GetProfileRequest)(nil),         // 5: realm.v1.GetProfileRequest
	(*ProfileResponse)(nil),           // 6: realm.v1.ProfileResponse
	(*UpdateProfileRequest)(nil),      // 7: realm.v1.UpdateProfileRequest
	(*SetPasswordRequest)(nil),        // 8: realm.v1.SetPasswordRequest
	(*SetPasswordResponse)(nil),       // 9: realm.v1.SetPasswordResponse
	(*CheckAvailabilityRequest)(nil),  // 10: realm.v1.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 11: realm.v1.CheckAvailabilityResponse
	(*UnlinkOAuthRequest)(nil),        // 12: realm.v1.UnlinkOAuthRequest
	(*UnlinkOAuthResponse)(nil),       // 13: realm.v1.UnlinkOAuthResponse
}
var file_proto_realm_v1_auth_proto_depIdxs = []int32{
	0,  // 0: realm.v1.User.connected_accounts:type_name -> realm.v1.OAuthAccount
	1,  // 1: realm.v1.AuthResponse.user:type_name -> realm.v1.User
	1,  // 2: realm.v1.ProfileResponse.user:type_name -> realm.v1.User
	2,  // 3: realm.v1.AuthService.Register:input_type -> realm.v1.RegisterRequest
	3,  // 4: realm.v1.AuthService.Login:input_type -> realm.v1.LoginRequest
	5,  // 5: realm.v1.AuthService.GetProfile:input_type -> realm.v1.GetProfileRequest
	7,  // 6: realm.v1.AuthService.UpdateProfile:input_type -> realm.v1.UpdateProfileRequest
	8,  // 7: realm.v1.AuthService.SetPassword:input_type -> realm.v1.SetPasswordRequest
	10, // 8: realm.v1.AuthService.CheckAvailability:input_type -> realm.v1.CheckAvailabilityRequest
	12, // 9: realm.v1.AuthService.UnlinkOAuth:input_type -> realm.v1.UnlinkOAuthRequest
	4,  // 10: realm.v1.AuthService.Register:output_type -> realm.v1.AuthResponse
	4,  // 11: realm.v1.AuthService.Login:output_type -> realm.v1.AuthResponse
	6,  // 12: realm.v1.AuthService.GetProfile:output_type -> realm.v1.ProfileResponse
	6,  // 13: realm.v1.AuthService.UpdateProfile:output_type -> realm.v1.ProfileResponse
	9,  // 14: realm.v1.AuthService.SetPassword:output_type -> realm.v1.SetPasswordResponse
	11, // 15: realm.v1.AuthService.CheckAvailability:output_type -> realm.v1.CheckAvailabilityResponse
	13, // 16: realm.v1.AuthService.UnlinkOAuth:output_type -> realm.v1.UnlinkOAuthResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_realm_v1_auth_proto_init() }
func file_proto_realm_v1_auth_proto_init() {
	if File_proto_realm_v1_auth_proto != nil {
		return
	}
	file_proto_realm_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_realm_v1_auth_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realm_v1_auth_proto_rawDesc), len(file_proto_realm_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realm_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_realm_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_realm_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_realm_v1_auth_proto = out.File
	file_proto_realm_v1_auth_proto_goTypes = nil
	file_proto_realm_v1_auth_proto_depIdxs = nil
}
