// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/realm/v1/contact.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Gotcha        string                 `protobuf:"bytes,5,opt,name=gotcha,proto3" json:"gotcha,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_realm_v1_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_contact_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetGotcha() string {
	if x != nil {
		return x.Gotcha
	}
	return ""
}

func (x *SendMessageRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SendMessageRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_realm_v1_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_contact_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_realm_v1_contact_proto protoreflect.FileDescriptor

const file_proto_realm_v1_contact_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/realm/v1/contact.proto\x12\brealm.v1\"\xc8\x01\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06gotcha\x18\x05 \x01(\tR\x06gotcha\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\"G\n" +
	"\x13SendMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\\\n" +
	"\x0eContactService\x12J\n" +
	"\vSendMessage\x12\x1c.realm.v1.SendMessageRequest\x1a\x1d.realm.v1.SendMessageResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_proto_realm_v1_contact_proto_rawDescOnce sync.Once
	file_proto_realm_v1_contact_proto_rawDescData []byte
)

func file_proto_realm_v1_contact_proto_rawDescGZIP() []byte {
	file_proto_realm_v1_contact_proto_rawDescOnce.Do(func() {
		file_proto_realm_v1_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realm_v1_contact_proto_rawDesc), len(file_proto_realm_v1_contact_proto_rawDesc)))
	})
	return file_proto_realm_v1_contact_proto_rawDescData
}

var file_proto_realm_v1_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_realm_v1_contact_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: realm.v1.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: realm.v1.SendMessageResponse
}
var file_proto_realm_v1_contact_proto_depIdxs = []int32{
	0, // 0: realm.v1.ContactService.SendMessage:input_type -> realm.v1.SendMessageRequest
	1, // 1: realm.v1.ContactService.SendMessage:output_type -> realm.v1.SendMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_realm_v1_contact_proto_init() }
func file_proto_realm_v1_contact_proto_init() {
	if File_proto_realm_v1_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realm_v1_contact_proto_rawDesc), len(file_proto_realm_v1_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realm_v1_contact_proto_goTypes,
		DependencyIndexes: file_proto_realm_v1_contact_proto_depIdxs,
		MessageInfos:      file_proto_realm_v1_contact_proto_msgTypes,
	}.Build()
	File_proto_realm_v1_contact_proto = out.File
	file_proto_realm_v1_contact_proto_goTypes = nil
	file_proto_realm_v1_contact_proto_depIdxs = nil
}
