// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/realm/v1/lastfm.proto

package realmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LastFMService_GetRecentTracks_FullMethodName = "/realm.v1.LastFMService/GetRecentTracks"
	LastFMService_GetUserInfo_FullMethodName     = "/realm.v1.LastFMService/GetUserInfo"
)

// LastFMServiceClient is the client API for LastFMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LastFMServiceClient interface {
	GetRecentTracks(ctx context.Context, in *GetRecentTracksRequest, opts ...grpc.CallOption) (*RecentTracksResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type lastFMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLastFMServiceClient(cc grpc.ClientConnInterface) LastFMServiceClient {
	return &lastFMServiceClient{cc}
}

func (c *lastFMServiceClient) GetRecentTracks(ctx context.Context, in *GetRecentTracksRequest, opts ...grpc.CallOption) (*RecentTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecentTracksResponse)
	err := c.cc.Invoke(ctx, LastFMService_GetRecentTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lastFMServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, LastFMService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LastFMServiceServer is the server API for LastFMService service.
// All implementations must embed UnimplementedLastFMServiceServer
// for forward compatibility.
type LastFMServiceServer interface {
	GetRecentTracks(context.Context, *GetRecentTracksRequest) (*RecentTracksResponse, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*UserInfoResponse, error)
	mustEmbedUnimplementedLastFMServiceServer()
}

// UnimplementedLastFMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLastFMServiceServer struct{}

func (UnimplementedLastFMServiceServer) GetRecentTracks(context.Context, *GetRecentTracksRequest) (*RecentTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentTracks not implemented")
}
func (UnimplementedLastFMServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedLastFMServiceServer) mustEmbedUnimplementedLastFMServiceServer() {}
func (UnimplementedLastFMServiceServer) testEmbeddedByValue()                       {}

// UnsafeLastFMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LastFMServiceServer will
// result in compilation errors.
type UnsafeLastFMServiceServer interface {
	mustEmbedUnimplementedLastFMServiceServer()
}

func RegisterLastFMServiceServer(s grpc.ServiceRegistrar, srv LastFMServiceServer) {
	// If the following call panics, it indicates UnimplementedLastFMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LastFMService_ServiceDesc, srv)
}

func _LastFMService_GetRecentTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LastFMServiceServer).GetRecentTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LastFMService_GetRecentTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LastFMServiceServer).GetRecentTracks(ctx, req.(*GetRecentTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LastFMService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LastFMServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LastFMService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LastFMServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LastFMService_ServiceDesc is the grpc.ServiceDesc for LastFMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LastFMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realm.v1.LastFMService",
	HandlerType: (*LastFMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecentTracks",
			Handler:    _LastFMService_GetRecentTracks_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _LastFMService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/realm/v1/lastfm.proto",
}
