// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/realm/v1/lastfm.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LastFMImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMImage) Reset() {
	*x = LastFMImage{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMImage) ProtoMessage() {}

func (x *LastFMImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMImage.ProtoReflect.Descriptor instead.
func (*LastFMImage) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{0}
}

func (x *LastFMImage) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *LastFMImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LastFMTrackArtist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mbid          string                 `protobuf:"bytes,1,opt,name=mbid,proto3" json:"mbid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMTrackArtist) Reset() {
	*x = LastFMTrackArtist{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMTrackArtist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMTrackArtist) ProtoMessage() {}

func (x *LastFMTrackArtist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMTrackArtist.ProtoReflect.Descriptor instead.
func (*LastFMTrackArtist) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{1}
}

func (x *LastFMTrackArtist) GetMbid() string {
	if x != nil {
		return x.Mbid
	}
	return ""
}

func (x *LastFMTrackArtist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LastFMTrackAlbum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mbid          string                 `protobuf:"bytes,1,opt,name=mbid,proto3" json:"mbid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMTrackAlbum) Reset() {
	*x = LastFMTrackAlbum{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMTrackAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMTrackAlbum) ProtoMessage() {}

func (x *LastFMTrackAlbum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMTrackAlbum.ProtoReflect.Descriptor instead.
func (*LastFMTrackAlbum) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{2}
}

func (x *LastFMTrackAlbum) GetMbid() string {
	if x != nil {
		return x.Mbid
	}
	return ""
}

func (x *LastFMTrackAlbum) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type LastFMTrackDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uts           string                 `protobuf:"bytes,1,opt,name=uts,proto3" json:"uts,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMTrackDate) Reset() {
	*x = LastFMTrackDate{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMTrackDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMTrackDate) ProtoMessage() {}

func (x *LastFMTrackDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMTrackDate.ProtoReflect.Descriptor instead.
func (*LastFMTrackDate) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{3}
}

func (x *LastFMTrackDate) GetUts() string {
	if x != nil {
		return x.Uts
	}
	return ""
}

func (x *LastFMTrackDate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LastFMTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mbid          string                 `protobuf:"bytes,2,opt,name=mbid,proto3" json:"mbid,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Streamable    string                 `protobuf:"bytes,4,opt,name=streamable,proto3" json:"streamable,omitempty"`
	Artist        *LastFMTrackArtist     `protobuf:"bytes,5,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         *LastFMTrackAlbum      `protobuf:"bytes,6,opt,name=album,proto3" json:"album,omitempty"`
	Images        []*LastFMImage         `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Date          *LastFMTrackDate       `protobuf:"bytes,8,opt,name=date,proto3,oneof" json:"date,omitempty"`
	NowPlaying    bool                   `protobuf:"varint,9,opt,name=now_playing,json=nowPlaying,proto3" json:"now_playing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMTrack) Reset() {
	*x = LastFMTrack{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMTrack) ProtoMessage() {}

func (x *LastFMTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMTrack.ProtoReflect.Descriptor instead.
func (*LastFMTrack) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{4}
}

func (x *LastFMTrack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LastFMTrack) GetMbid() string {
	if x != nil {
		return x.Mbid
	}
	return ""
}

func (x *LastFMTrack) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LastFMTrack) GetStreamable() string {
	if x != nil {
		return x.Streamable
	}
	return ""
}

func (x *LastFMTrack) GetArtist() *LastFMTrackArtist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *LastFMTrack) GetAlbum() *LastFMTrackAlbum {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *LastFMTrack) GetImages() []*LastFMImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *LastFMTrack) GetDate() *LastFMTrackDate {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *LastFMTrack) GetNowPlaying() bool {
	if x != nil {
		return x.NowPlaying
	}
	return false
}

type LastFMRecentTracksAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          string                 `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Total         string                 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	PerPage       string                 `protobuf:"bytes,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    string                 `protobuf:"bytes,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMRecentTracksAttr) Reset() {
	*x = LastFMRecentTracksAttr{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMRecentTracksAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMRecentTracksAttr) ProtoMessage() {}

func (x *LastFMRecentTracksAttr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMRecentTracksAttr.ProtoReflect.Descriptor instead.
func (*LastFMRecentTracksAttr) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{5}
}

func (x *LastFMRecentTracksAttr) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *LastFMRecentTracksAttr) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *LastFMRecentTracksAttr) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LastFMRecentTracksAttr) GetPerPage() string {
	if x != nil {
		return x.PerPage
	}
	return ""
}

func (x *LastFMRecentTracksAttr) GetTotalPages() string {
	if x != nil {
		return x.TotalPages
	}
	return ""
}

type GetRecentTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTracksRequest) Reset() {
	*x = GetRecentTracksRequest{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTracksRequest) ProtoMessage() {}

func (x *GetRecentTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTracksRequest.ProtoReflect.Descriptor instead.
func (*GetRecentTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentTracksRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetRecentTracksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentTracksResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Attr          *LastFMRecentTracksAttr `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Tracks        []*LastFMTrack          `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	RawJson       string                  `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTracksResponse) Reset() {
	*x = RecentTracksResponse{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTracksResponse) ProtoMessage() {}

func (x *RecentTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTracksResponse.ProtoReflect.Descriptor instead.
func (*RecentTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{7}
}

func (x *RecentTracksResponse) GetAttr() *LastFMRecentTracksAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *RecentTracksResponse) GetTracks() []*LastFMTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *RecentTracksResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LastFMUserRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixTime      string                 `protobuf:"bytes,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMUserRegistered) Reset() {
	*x = LastFMUserRegistered{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMUserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMUserRegistered) ProtoMessage() {}

func (x *LastFMUserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMUserRegistered.ProtoReflect.Descriptor instead.
func (*LastFMUserRegistered) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{9}
}

func (x *LastFMUserRegistered) GetUnixTime() string {
	if x != nil {
		return x.UnixTime
	}
	return ""
}

func (x *LastFMUserRegistered) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LastFMUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Age           string                 `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Subscriber    string                 `protobuf:"bytes,6,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	PlayCount     string                 `protobuf:"bytes,7,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	ArtistCount   string                 `protobuf:"bytes,8,opt,name=artist_count,json=artistCount,proto3" json:"artist_count,omitempty"`
	TrackCount    string                 `protobuf:"bytes,9,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	AlbumCount    string                 `protobuf:"bytes,10,opt,name=album_count,json=albumCount,proto3" json:"album_count,omitempty"`
	Playlists     string                 `protobuf:"bytes,11,opt,name=playlists,proto3" json:"playlists,omitempty"`
	Url           string                 `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	Images        []*LastFMImage         `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty"`
	Registered    *LastFMUserRegistered  `protobuf:"bytes,15,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastFMUser) Reset() {
	*x = LastFMUser{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastFMUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastFMUser) ProtoMessage() {}

func (x *LastFMUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastFMUser.ProtoReflect.Descriptor instead.
func (*LastFMUser) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{10}
}

func (x *LastFMUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LastFMUser) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *LastFMUser) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LastFMUser) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *LastFMUser) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *LastFMUser) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *LastFMUser) GetPlayCount() string {
	if x != nil {
		return x.PlayCount
	}
	return ""
}

func (x *LastFMUser) GetArtistCount() string {
	if x != nil {
		return x.ArtistCount
	}
	return ""
}

func (x *LastFMUser) GetTrackCount() string {
	if x != nil {
		return x.TrackCount
	}
	return ""
}

func (x *LastFMUser) GetAlbumCount() string {
	if x != nil {
		return x.AlbumCount
	}
	return ""
}

func (x *LastFMUser) GetPlaylists() string {
	if x != nil {
		return x.Playlists
	}
	return ""
}

func (x *LastFMUser) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LastFMUser) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LastFMUser) GetImages() []*LastFMImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *LastFMUser) GetRegistered() *LastFMUserRegistered {
	if x != nil {
		return x.Registered
	}
	return nil
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *LastFMUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RawJson       string                 `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_lastfm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_lastfm_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfoResponse) GetUser() *LastFMUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserInfoResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_proto_realm_v1_lastfm_proto protoreflect.FileDescriptor

const file_proto_realm_v1_lastfm_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/realm/v1/lastfm.proto\x12\brealm.v1\"3\n" +
	"\vLastFMImage\x12\x12\n" +
	"\x04size\x18\x01 \x01(\tR\x04size\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\";\n" +
	"\x11LastFMTrackArtist\x12\x12\n" +
	"\x04mbid\x18\x01 \x01(\tR\x04mbid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\x10LastFMTrackAlbum\x12\x12\n" +
	"\x04mbid\x18\x01 \x01(\tR\x04mbid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"7\n" +
	"\x0fLastFMTrackDate\x12\x10\n" +
	"\x03uts\x18\x01 \x01(\tR\x03uts\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xdb\x02\n" +
	"\vLastFMTrack\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mbid\x18\x02 \x01(\tR\x04mbid\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"streamable\x18\x04 \x01(\tR\n" +
	"streamable\x123\n" +
	"\x06artist\x18\x05 \x01(\v2\x1b.realm.v1.LastFMTrackArtistR\x06artist\x120\n" +
	"\x05album\x18\x06 \x01(\v2\x1a.realm.v1.LastFMTrackAlbumR\x05album\x12-\n" +
	"\x06images\x18\a \x03(\v2\x15.realm.v1.LastFMImageR\x06images\x122\n" +
	"\x04date\x18\b \x01(\v2\x19.realm.v1.LastFMTrackDateH\x00R\x04date\x88\x01\x01\x12\x1f\n" +
	"\vnow_playing\x18\t \x01(\bR\n" +
	"nowPlayingB\a\n" +
	"\x05_date\"\x92\x01\n" +
	"\x16LastFMRecentTracksAttr\x12\x12\n" +
	"\x04page\x18\x01 \x01(\tR\x04page\x12\x14\n" +
	"\x05total\x18\x02 \x01(\tR\x05total\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\tR\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\tR\n" +
	"totalPages\"J\n" +
	"\x16GetRecentTracksRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x96\x01\n" +
	"\x14RecentTracksResponse\x124\n" +
	"\x04attr\x18\x01 \x01(\v2 .realm.v1.LastFMRecentTracksAttrR\x04attr\x12-\n" +
	"\x06tracks\x18\x02 \x03(\v2\x15.realm.v1.LastFMTrackR\x06tracks\x12\x19\n" +
	"\braw_json\x18\x03 \x01(\tR\arawJson\"0\n" +
	"\x12GetUserInfoRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"G\n" +
	"\x14LastFMUserRegistered\x12\x1b\n" +
	"\tunix_time\x18\x01 \x01(\tR\bunixTime\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xd8\x03\n" +
	"\n" +
	"LastFMUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x06 \x01(\tR\n" +
	"subscriber\x12\x1d\n" +
	"\n" +
	"play_count\x18\a \x01(\tR\tplayCount\x12!\n" +
	"\fartist_count\x18\b \x01(\tR\vartistCount\x12\x1f\n" +
	"\vtrack_count\x18\t \x01(\tR\n" +
	"trackCount\x12\x1f\n" +
	"\valbum_count\x18\n" +
	" \x01(\tR\n" +
	"albumCount\x12\x1c\n" +
	"\tplaylists\x18\v \x01(\tR\tplaylists\x12\x10\n" +
	"\x03url\x18\f \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\x12-\n" +
	"\x06images\x18\x0e \x03(\v2\x15.realm.v1.LastFMImageR\x06images\x12>\n" +
	"\n" +
	"registered\x18\x0f \x01(\v2\x1e.realm.v1.LastFMUserRegisteredR\n" +
	"registered\"W\n" +
	"\x10UserInfoResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.realm.v1.LastFMUserR\x04user\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\tR\arawJson2\xad\x01\n" +
	"\rLastFMService\x12S\n" +
	"\x0fGetRecentTracks\x12 .realm.v1.GetRecentTracksRequest\x1a\x1e.realm.v1.RecentTracksResponse\x12G\n" +
	"\vGetUserInfo\x12\x1c.realm.v1.GetUserInfoRequest\x1a\x1a.realm.v1.UserInfoResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_proto_realm_v1_lastfm_proto_rawDescOnce sync.Once
	file_proto_realm_v1_lastfm_proto_rawDescData []byte
)

func file_proto_realm_v1_lastfm_proto_rawDescGZIP() []byte {
	file_proto_realm_v1_lastfm_proto_rawDescOnce.Do(func() {
		file_proto_realm_v1_lastfm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realm_v1_lastfm_proto_rawDesc), len(file_proto_realm_v1_lastfm_proto_rawDesc)))
	})
	return file_proto_realm_v1_lastfm_proto_rawDescData
}

var file_proto_realm_v1_lastfm_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_realm_v1_lastfm_proto_goTypes = []any{
	(*LastFMImage)(nil),            // 0: realm.v1.LastFMImage
	(*LastFMTrackArtist)(nil),      // 1: realm.v1.LastFMTrackArtist
	(*LastFMTrackAlbum)(nil),       // 2: realm.v1.LastFMTrackAlbum
	(*LastFMTrackDate)(nil),        // 3: realm.v1.LastFMTrackDate
	(*LastFMTrack)(nil),            // 4: realm.v1.LastFMTrack
	(*LastFMRecentTracksAttr)(nil), // 5: realm.v1.LastFMRecentTracksAttr
	(*GetRecentTracksRequest)(nil), // 6: realm.v1.GetRecentTracksRequest
	(*RecentTracksResponse)(nil),   // 7: realm.v1.RecentTracksResponse
	(*GetUserInfoRequest)(nil),     // 8: realm.v1.GetUserInfoRequest
	(*LastFMUserRegistered)(nil),   // 9: realm.v1.LastFMUserRegistered
	(*LastFMUser)(nil),             // 10: realm.v1.LastFMUser
	(*UserInfoResponse)(nil),       // 11: realm.v1.UserInfoResponse
}
var file_proto_realm_v1_lastfm_proto_depIdxs = []int32{
	1,  // 0: realm.v1.LastFMTrack.artist:type_name -> realm.v1.LastFMTrackArtist
	2,  // 1: realm.v1.LastFMTrack.album:type_name -> realm.v1.LastFMTrackAlbum
	0,  // 2: realm.v1.LastFMTrack.images:type_name -> realm.v1.LastFMImage
	3,  // 3: realm.v1.LastFMTrack.date:type_name -> realm.v1.LastFMTrackDate
	5,  // 4: realm.v1.RecentTracksResponse.attr:type_name -> realm.v1.LastFMRecentTracksAttr
	4,  // 5: realm.v1.RecentTracksResponse.tracks:type_name -> realm.v1.LastFMTrack
	0,  // 6: realm.v1.LastFMUser.images:type_name -> realm.v1.LastFMImage
	9,  // 7: realm.v1.LastFMUser.registered:type_name -> realm.v1.LastFMUserRegistered
	10, // 8: realm.v1.UserInfoResponse.user:type_name -> realm.v1.LastFMUser
	6,  // 9: realm.v1.LastFMService.GetRecentTracks:input_type -> realm.v1.GetRecentTracksRequest
	8,  // 10: realm.v1.LastFMService.GetUserInfo:input_type -> realm.v1.GetUserInfoRequest
	7,  // 11: realm.v1.LastFMService.GetRecentTracks:output_type -> realm.v1.RecentTracksResponse
	11, // 12: realm.v1.LastFMService.GetUserInfo:output_type -> realm.v1.UserInfoResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_realm_v1_lastfm_proto_init() }
func file_proto_realm_v1_lastfm_proto_init() {
	if File_proto_realm_v1_lastfm_proto != nil {
		return
	}
	file_proto_realm_v1_lastfm_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realm_v1_lastfm_proto_rawDesc), len(file_proto_realm_v1_lastfm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realm_v1_lastfm_proto_goTypes,
		DependencyIndexes: file_proto_realm_v1_lastfm_proto_depIdxs,
		MessageInfos:      file_proto_realm_v1_lastfm_proto_msgTypes,
	}.Build()
	File_proto_realm_v1_lastfm_proto = out.File
	file_proto_realm_v1_lastfm_proto_goTypes = nil
	file_proto_realm_v1_lastfm_proto_depIdxs = nil
}
