// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: realm/v1/log.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level          string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Component      string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	TraceId        string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId         string                 `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	AttributesJson string                 `protobuf:"bytes,8,opt,name=attributes_json,json=attributesJson,proto3" json:"attributes_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_realm_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEntry) GetAttributesJson() string {
	if x != nil {
		return x.AttributesJson
	}
	return ""
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Level         *string                `protobuf:"bytes,3,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	TraceId       *string                `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_realm_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *GetLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetLogsRequest) GetLevel() string {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ""
}

func (x *GetLogsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetLogsRequest) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_realm_v1_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type DeleteLogsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BeforeTimestamp *string                `protobuf:"bytes,1,opt,name=before_timestamp,json=beforeTimestamp,proto3,oneof" json:"before_timestamp,omitempty"`
	LogId           *string                `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3,oneof" json:"log_id,omitempty"`
	ClearAll        bool                   `protobuf:"varint,3,opt,name=clear_all,json=clearAll,proto3" json:"clear_all,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteLogsRequest) Reset() {
	*x = DeleteLogsRequest{}
	mi := &file_realm_v1_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogsRequest) ProtoMessage() {}

func (x *DeleteLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogsRequest.ProtoReflect.Descriptor instead.
func (*DeleteLogsRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLogsRequest) GetBeforeTimestamp() string {
	if x != nil && x.BeforeTimestamp != nil {
		return *x.BeforeTimestamp
	}
	return ""
}

func (x *DeleteLogsRequest) GetLogId() string {
	if x != nil && x.LogId != nil {
		return *x.LogId
	}
	return ""
}

func (x *DeleteLogsRequest) GetClearAll() bool {
	if x != nil {
		return x.ClearAll
	}
	return false
}

type DeleteLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogsResponse) Reset() {
	*x = DeleteLogsResponse{}
	mi := &file_realm_v1_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogsResponse) ProtoMessage() {}

func (x *DeleteLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogsResponse.ProtoReflect.Descriptor instead.
func (*DeleteLogsResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLogsResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteLogsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *string                `protobuf:"bytes,1,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Search        *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_realm_v1_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_log_proto_rawDescGZIP(), []int{5}
}

func (x *StreamLogsRequest) GetLevel() string {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ""
}

func (x *StreamLogsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

var File_realm_v1_log_proto protoreflect.FileDescriptor

const file_realm_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x12realm/v1/log.proto\x12\brealm.v1\"\xe3\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\tR\x06spanId\x12'\n" +
	"\x0fattributes_json\x18\b \x01(\tR\x0eattributesJson\"\xb8\x01\n" +
	"\x0eGetLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x19\n" +
	"\x05level\x18\x03 \x01(\tH\x00R\x05level\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x01R\x06search\x88\x01\x01\x12\x1e\n" +
	"\btrace_id\x18\x05 \x01(\tH\x02R\atraceId\x88\x01\x01B\b\n" +
	"\x06_levelB\t\n" +
	"\a_searchB\v\n" +
	"\t_trace_id\"O\n" +
	"\x0fGetLogsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04logs\x18\x02 \x03(\v2\x12.realm.v1.LogEntryR\x04logs\"\x9c\x01\n" +
	"\x11DeleteLogsRequest\x12.\n" +
	"\x10before_timestamp\x18\x01 \x01(\tH\x00R\x0fbeforeTimestamp\x88\x01\x01\x12\x1a\n" +
	"\x06log_id\x18\x02 \x01(\tH\x01R\x05logId\x88\x01\x01\x12\x1b\n" +
	"\tclear_all\x18\x03 \x01(\bR\bclearAllB\x13\n" +
	"\x11_before_timestampB\t\n" +
	"\a_log_id\"k\n" +
	"\x12DeleteLogsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"`\n" +
	"\x11StreamLogsRequest\x12\x19\n" +
	"\x05level\x18\x01 \x01(\tH\x00R\x05level\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x01R\x06search\x88\x01\x01B\b\n" +
	"\x06_levelB\t\n" +
	"\a_search2\xd6\x01\n" +
	"\n" +
	"LogService\x12>\n" +
	"\aGetLogs\x12\x18.realm.v1.GetLogsRequest\x1a\x19.realm.v1.GetLogsResponse\x12G\n" +
	"\n" +
	"DeleteLogs\x12\x1b.realm.v1.DeleteLogsRequest\x1a\x1c.realm.v1.DeleteLogsResponse\x12?\n" +
	"\n" +
	"StreamLogs\x12\x1b.realm.v1.StreamLogsRequest\x1a\x12.realm.v1.LogEntry0\x01B;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_realm_v1_log_proto_rawDescOnce sync.Once
	file_realm_v1_log_proto_rawDescData []byte
)

func file_realm_v1_log_proto_rawDescGZIP() []byte {
	file_realm_v1_log_proto_rawDescOnce.Do(func() {
		file_realm_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realm_v1_log_proto_rawDesc), len(file_realm_v1_log_proto_rawDesc)))
	})
	return file_realm_v1_log_proto_rawDescData
}

var file_realm_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_realm_v1_log_proto_goTypes = []any{
	(*LogEntry)(nil),           // 0: realm.v1.LogEntry
	(*GetLogsRequest)(nil),     // 1: realm.v1.GetLogsRequest
	(*GetLogsResponse)(nil),    // 2: realm.v1.GetLogsResponse
	(*DeleteLogsRequest)(nil),  // 3: realm.v1.DeleteLogsRequest
	(*DeleteLogsResponse)(nil), // 4: realm.v1.DeleteLogsResponse
	(*StreamLogsRequest)(nil),  // 5: realm.v1.StreamLogsRequest
}
var file_realm_v1_log_proto_depIdxs = []int32{
	0, // 0: realm.v1.GetLogsResponse.logs:type_name -> realm.v1.LogEntry
	1, // 1: realm.v1.LogService.GetLogs:input_type -> realm.v1.GetLogsRequest
	3, // 2: realm.v1.LogService.DeleteLogs:input_type -> realm.v1.DeleteLogsRequest
	5, // 3: realm.v1.LogService.StreamLogs:input_type -> realm.v1.StreamLogsRequest
	2, // 4: realm.v1.LogService.GetLogs:output_type -> realm.v1.GetLogsResponse
	4, // 5: realm.v1.LogService.DeleteLogs:output_type -> realm.v1.DeleteLogsResponse
	0, // 6: realm.v1.LogService.StreamLogs:output_type -> realm.v1.LogEntry
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_realm_v1_log_proto_init() }
func file_realm_v1_log_proto_init() {
	if File_realm_v1_log_proto != nil {
		return
	}
	file_realm_v1_log_proto_msgTypes[1].OneofWrappers = []any{}
	file_realm_v1_log_proto_msgTypes[3].OneofWrappers = []any{}
	file_realm_v1_log_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realm_v1_log_proto_rawDesc), len(file_realm_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realm_v1_log_proto_goTypes,
		DependencyIndexes: file_realm_v1_log_proto_depIdxs,
		MessageInfos:      file_realm_v1_log_proto_msgTypes,
	}.Build()
	File_realm_v1_log_proto = out.File
	file_realm_v1_log_proto_goTypes = nil
	file_realm_v1_log_proto_depIdxs = nil
}
