// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/realm/v1/reaction.proto

package realmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReactionService_GetReactions_FullMethodName   = "/realm.v1.ReactionService/GetReactions"
	ReactionService_ToggleReaction_FullMethodName = "/realm.v1.ReactionService/ToggleReaction"
)

// ReactionServiceClient is the client API for ReactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReactionServiceClient interface {
	GetReactions(ctx context.Context, in *GetReactionsRequest, opts ...grpc.CallOption) (*ReactionsResponse, error)
	ToggleReaction(ctx context.Context, in *ToggleReactionRequest, opts ...grpc.CallOption) (*ToggleReactionResponse, error)
}

type reactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReactionServiceClient(cc grpc.ClientConnInterface) ReactionServiceClient {
	return &reactionServiceClient{cc}
}

func (c *reactionServiceClient) GetReactions(ctx context.Context, in *GetReactionsRequest, opts ...grpc.CallOption) (*ReactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReactionsResponse)
	err := c.cc.Invoke(ctx, ReactionService_GetReactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) ToggleReaction(ctx context.Context, in *ToggleReactionRequest, opts ...grpc.CallOption) (*ToggleReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleReactionResponse)
	err := c.cc.Invoke(ctx, ReactionService_ToggleReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactionServiceServer is the server API for ReactionService service.
// All implementations must embed UnimplementedReactionServiceServer
// for forward compatibility.
type ReactionServiceServer interface {
	GetReactions(context.Context, *GetReactionsRequest) (*ReactionsResponse, error)
	ToggleReaction(context.Context, *ToggleReactionRequest) (*ToggleReactionResponse, error)
	mustEmbedUnimplementedReactionServiceServer()
}

// UnimplementedReactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReactionServiceServer struct{}

func (UnimplementedReactionServiceServer) GetReactions(context.Context, *GetReactionsRequest) (*ReactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReactions not implemented")
}
func (UnimplementedReactionServiceServer) ToggleReaction(context.Context, *ToggleReactionRequest) (*ToggleReactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleReaction not implemented")
}
func (UnimplementedReactionServiceServer) mustEmbedUnimplementedReactionServiceServer() {}
func (UnimplementedReactionServiceServer) testEmbeddedByValue()                         {}

// UnsafeReactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReactionServiceServer will
// result in compilation errors.
type UnsafeReactionServiceServer interface {
	mustEmbedUnimplementedReactionServiceServer()
}

func RegisterReactionServiceServer(s grpc.ServiceRegistrar, srv ReactionServiceServer) {
	// If the following call panics, it indicates UnimplementedReactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReactionService_ServiceDesc, srv)
}

func _ReactionService_GetReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).GetReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_GetReactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).GetReactions(ctx, req.(*GetReactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_ToggleReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).ToggleReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReactionService_ToggleReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).ToggleReaction(ctx, req.(*ToggleReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReactionService_ServiceDesc is the grpc.ServiceDesc for ReactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realm.v1.ReactionService",
	HandlerType: (*ReactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReactions",
			Handler:    _ReactionService_GetReactions_Handler,
		},
		{
			MethodName: "ToggleReaction",
			Handler:    _ReactionService_ToggleReaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/realm/v1/reaction.proto",
}
