// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/realm/v1/reaction.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsRequest) Reset() {
	*x = GetReactionsRequest{}
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsRequest) ProtoMessage() {}

func (x *GetReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_reaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetReactionsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ReactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Reactions     map[string]int32       `protobuf:"bytes,3,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UserReaction  *string                `protobuf:"bytes,4,opt,name=user_reaction,json=userReaction,proto3,oneof" json:"user_reaction,omitempty"`
	UserReactions []string               `protobuf:"bytes,5,rep,name=user_reactions,json=userReactions,proto3" json:"user_reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionsResponse) Reset() {
	*x = ReactionsResponse{}
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionsResponse) ProtoMessage() {}

func (x *ReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionsResponse.ProtoReflect.Descriptor instead.
func (*ReactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_reaction_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionsResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ReactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ReactionsResponse) GetReactions() map[string]int32 {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *ReactionsResponse) GetUserReaction() string {
	if x != nil && x.UserReaction != nil {
		return *x.UserReaction
	}
	return ""
}

func (x *ReactionsResponse) GetUserReactions() []string {
	if x != nil {
		return x.UserReactions
	}
	return nil
}

type ToggleReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReactionRequest) Reset() {
	*x = ToggleReactionRequest{}
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReactionRequest) ProtoMessage() {}

func (x *ToggleReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReactionRequest.ProtoReflect.Descriptor instead.
func (*ToggleReactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_reaction_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleReactionRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ToggleReactionRequest) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type ToggleReactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Reactions     map[string]int32       `protobuf:"bytes,5,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UserReaction  *string                `protobuf:"bytes,6,opt,name=user_reaction,json=userReaction,proto3,oneof" json:"user_reaction,omitempty"`
	UserReactions []string               `protobuf:"bytes,7,rep,name=user_reactions,json=userReactions,proto3" json:"user_reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReactionResponse) Reset() {
	*x = ToggleReactionResponse{}
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReactionResponse) ProtoMessage() {}

func (x *ToggleReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_reaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReactionResponse.ProtoReflect.Descriptor instead.
func (*ToggleReactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_reaction_proto_rawDescGZIP(), []int{3}
}

func (x *ToggleReactionResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ToggleReactionResponse) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *ToggleReactionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ToggleReactionResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ToggleReactionResponse) GetReactions() map[string]int32 {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *ToggleReactionResponse) GetUserReaction() string {
	if x != nil && x.UserReaction != nil {
		return *x.UserReaction
	}
	return ""
}

func (x *ToggleReactionResponse) GetUserReactions() []string {
	if x != nil {
		return x.UserReactions
	}
	return nil
}

var File_proto_realm_v1_reaction_proto protoreflect.FileDescriptor

const file_proto_realm_v1_reaction_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/realm/v1/reaction.proto\x12\brealm.v1\")\n" +
	"\x13GetReactionsRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xb3\x02\n" +
	"\x11ReactionsResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12H\n" +
	"\treactions\x18\x03 \x03(\v2*.realm.v1.ReactionsResponse.ReactionsEntryR\treactions\x12(\n" +
	"\ruser_reaction\x18\x04 \x01(\tH\x00R\fuserReaction\x88\x01\x01\x12%\n" +
	"\x0euser_reactions\x18\x05 \x03(\tR\ruserReactions\x1a<\n" +
	"\x0eReactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x10\n" +
	"\x0e_user_reaction\"G\n" +
	"\x15ToggleReactionRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\"\xf1\x02\n" +
	"\x16ToggleReactionResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12M\n" +
	"\treactions\x18\x05 \x03(\v2/.realm.v1.ToggleReactionResponse.ReactionsEntryR\treactions\x12(\n" +
	"\ruser_reaction\x18\x06 \x01(\tH\x00R\fuserReaction\x88\x01\x01\x12%\n" +
	"\x0euser_reactions\x18\a \x03(\tR\ruserReactions\x1a<\n" +
	"\x0eReactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x10\n" +
	"\x0e_user_reaction2\xb2\x01\n" +
	"\x0fReactionService\x12J\n" +
	"\fGetReactions\x12\x1d.realm.v1.GetReactionsRequest\x1a\x1b.realm.v1.ReactionsResponse\x12S\n" +
	"\x0eToggleReaction\x12\x1f.realm.v1.ToggleReactionRequest\x1a .realm.v1.ToggleReactionResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_proto_realm_v1_reaction_proto_rawDescOnce sync.Once
	file_proto_realm_v1_reaction_proto_rawDescData []byte
)

func file_proto_realm_v1_reaction_proto_rawDescGZIP() []byte {
	file_proto_realm_v1_reaction_proto_rawDescOnce.Do(func() {
		file_proto_realm_v1_reaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realm_v1_reaction_proto_rawDesc), len(file_proto_realm_v1_reaction_proto_rawDesc)))
	})
	return file_proto_realm_v1_reaction_proto_rawDescData
}

var file_proto_realm_v1_reaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_realm_v1_reaction_proto_goTypes = []any{
	(*GetReactionsRequest)(nil),    // 0: realm.v1.GetReactionsRequest
	(*ReactionsResponse)(nil),      // 1: realm.v1.ReactionsResponse
	(*ToggleReactionRequest)(nil),  // 2: realm.v1.ToggleReactionRequest
	(*ToggleReactionResponse)(nil), // 3: realm.v1.ToggleReactionResponse
	nil,                            // 4: realm.v1.ReactionsResponse.ReactionsEntry
	nil,                            // 5: realm.v1.ToggleReactionResponse.ReactionsEntry
}
var file_proto_realm_v1_reaction_proto_depIdxs = []int32{
	4, // 0: realm.v1.ReactionsResponse.reactions:type_name -> realm.v1.ReactionsResponse.ReactionsEntry
	5, // 1: realm.v1.ToggleReactionResponse.reactions:type_name -> realm.v1.ToggleReactionResponse.ReactionsEntry
	0, // 2: realm.v1.ReactionService.GetReactions:input_type -> realm.v1.GetReactionsRequest
	2, // 3: realm.v1.ReactionService.ToggleReaction:input_type -> realm.v1.ToggleReactionRequest
	1, // 4: realm.v1.ReactionService.GetReactions:output_type -> realm.v1.ReactionsResponse
	3, // 5: realm.v1.ReactionService.ToggleReaction:output_type -> realm.v1.ToggleReactionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_realm_v1_reaction_proto_init() }
func file_proto_realm_v1_reaction_proto_init() {
	if File_proto_realm_v1_reaction_proto != nil {
		return
	}
	file_proto_realm_v1_reaction_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_realm_v1_reaction_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realm_v1_reaction_proto_rawDesc), len(file_proto_realm_v1_reaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realm_v1_reaction_proto_goTypes,
		DependencyIndexes: file_proto_realm_v1_reaction_proto_depIdxs,
		MessageInfos:      file_proto_realm_v1_reaction_proto_msgTypes,
	}.Build()
	File_proto_realm_v1_reaction_proto = out.File
	file_proto_realm_v1_reaction_proto_goTypes = nil
	file_proto_realm_v1_reaction_proto_depIdxs = nil
}
