// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/realm/v1/storage.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	OriginalSize   int64                  `protobuf:"varint,4,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	CompressedSize int64                  `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3" json:"compressed_size,omitempty"`
	SavingsPercent float64                `protobuf:"fixed64,6,opt,name=savings_percent,json=savingsPercent,proto3" json:"savings_percent,omitempty"`
	Sha256         string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Blurhash       *string                `protobuf:"bytes,8,opt,name=blurhash,proto3,oneof" json:"blurhash,omitempty"`
	Width          *int32                 `protobuf:"varint,9,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height         *int32                 `protobuf:"varint,10,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Url            string                 `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	WebpUrl        *string                `protobuf:"bytes,12,opt,name=webp_url,json=webpUrl,proto3,oneof" json:"webp_url,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *FileMetadata) GetCompressedSize() int64 {
	if x != nil {
		return x.CompressedSize
	}
	return 0
}

func (x *FileMetadata) GetSavingsPercent() float64 {
	if x != nil {
		return x.SavingsPercent
	}
	return 0
}

func (x *FileMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileMetadata) GetBlurhash() string {
	if x != nil && x.Blurhash != nil {
		return *x.Blurhash
	}
	return ""
}

func (x *FileMetadata) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *FileMetadata) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *FileMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileMetadata) GetWebpUrl() string {
	if x != nil && x.WebpUrl != nil {
		return *x.WebpUrl
	}
	return ""
}

func (x *FileMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	File          *FileMetadata          `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetFile() *FileMetadata {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	File          *FileMetadata          `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetFileInfoResponse) GetFile() *FileMetadata {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Format        *string                `protobuf:"bytes,2,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetFileRequest) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

type FileChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunkResponse) Reset() {
	*x = FileChunkResponse{}
	mi := &file_proto_realm_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkResponse) ProtoMessage() {}

func (x *FileChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realm_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkResponse.ProtoReflect.Descriptor instead.
func (*FileChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_realm_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *FileChunkResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileChunkResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileChunkResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_realm_v1_storage_proto protoreflect.FileDescriptor

const file_proto_realm_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/realm/v1/storage.proto\x12\brealm.v1\"\xc5\x03\n" +
	"\fFileMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x03R\foriginalSize\x12'\n" +
	"\x0fcompressed_size\x18\x05 \x01(\x03R\x0ecompressedSize\x12'\n" +
	"\x0fsavings_percent\x18\x06 \x01(\x01R\x0esavingsPercent\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x12\x1f\n" +
	"\bblurhash\x18\b \x01(\tH\x00R\bblurhash\x88\x01\x01\x12\x19\n" +
	"\x05width\x18\t \x01(\x05H\x01R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\n" +
	" \x01(\x05H\x02R\x06height\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\x12\x1e\n" +
	"\bwebp_url\x18\f \x01(\tH\x03R\awebpUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAtB\v\n" +
	"\t_blurhashB\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\v\n" +
	"\t_webp_url\"f\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"r\n" +
	"\x12UploadFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04file\x18\x03 \x01(\v2\x16.realm.v1.FileMetadataR\x04file\"$\n" +
	"\x12GetFileInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x13GetFileInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12*\n" +
	"\x04file\x18\x02 \x01(\v2\x16.realm.v1.FileMetadataR\x04file\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12DeleteFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06format\x18\x02 \x01(\tH\x00R\x06format\x88\x01\x01B\t\n" +
	"\a_format\"h\n" +
	"\x11FileChunkResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename2\xb2\x02\n" +
	"\x0eStorageService\x12G\n" +
	"\n" +
	"UploadFile\x12\x1b.realm.v1.UploadFileRequest\x1a\x1c.realm.v1.UploadFileResponse\x12J\n" +
	"\vGetFileInfo\x12\x1c.realm.v1.GetFileInfoRequest\x1a\x1d.realm.v1.GetFileInfoResponse\x12G\n" +
	"\n" +
	"DeleteFile\x12\x1b.realm.v1.DeleteFileRequest\x1a\x1c.realm.v1.DeleteFileResponse\x12B\n" +
	"\aGetFile\x12\x18.realm.v1.GetFileRequest\x1a\x1b.realm.v1.FileChunkResponse0\x01B;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_proto_realm_v1_storage_proto_rawDescOnce sync.Once
	file_proto_realm_v1_storage_proto_rawDescData []byte
)

func file_proto_realm_v1_storage_proto_rawDescGZIP() []byte {
	file_proto_realm_v1_storage_proto_rawDescOnce.Do(func() {
		file_proto_realm_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realm_v1_storage_proto_rawDesc), len(file_proto_realm_v1_storage_proto_rawDesc)))
	})
	return file_proto_realm_v1_storage_proto_rawDescData
}

var file_proto_realm_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_realm_v1_storage_proto_goTypes = []any{
	(*FileMetadata)(nil),        // 0: realm.v1.FileMetadata
	(*UploadFileRequest)(nil),   // 1: realm.v1.UploadFileRequest
	(*UploadFileResponse)(nil),  // 2: realm.v1.UploadFileResponse
	(*GetFileInfoRequest)(nil),  // 3: realm.v1.GetFileInfoRequest
	(*GetFileInfoResponse)(nil), // 4: realm.v1.GetFileInfoResponse
	(*DeleteFileRequest)(nil),   // 5: realm.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),  // 6: realm.v1.DeleteFileResponse
	(*GetFileRequest)(nil),      // 7: realm.v1.GetFileRequest
	(*FileChunkResponse)(nil),   // 8: realm.v1.FileChunkResponse
}
var file_proto_realm_v1_storage_proto_depIdxs = []int32{
	0, // 0: realm.v1.UploadFileResponse.file:type_name -> realm.v1.FileMetadata
	0, // 1: realm.v1.GetFileInfoResponse.file:type_name -> realm.v1.FileMetadata
	1, // 2: realm.v1.StorageService.UploadFile:input_type -> realm.v1.UploadFileRequest
	3, // 3: realm.v1.StorageService.GetFileInfo:input_type -> realm.v1.GetFileInfoRequest
	5, // 4: realm.v1.StorageService.DeleteFile:input_type -> realm.v1.DeleteFileRequest
	7, // 5: realm.v1.StorageService.GetFile:input_type -> realm.v1.GetFileRequest
	2, // 6: realm.v1.StorageService.UploadFile:output_type -> realm.v1.UploadFileResponse
	4, // 7: realm.v1.StorageService.GetFileInfo:output_type -> realm.v1.GetFileInfoResponse
	6, // 8: realm.v1.StorageService.DeleteFile:output_type -> realm.v1.DeleteFileResponse
	8, // 9: realm.v1.StorageService.GetFile:output_type -> realm.v1.FileChunkResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_realm_v1_storage_proto_init() }
func file_proto_realm_v1_storage_proto_init() {
	if File_proto_realm_v1_storage_proto != nil {
		return
	}
	file_proto_realm_v1_storage_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_realm_v1_storage_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realm_v1_storage_proto_rawDesc), len(file_proto_realm_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realm_v1_storage_proto_goTypes,
		DependencyIndexes: file_proto_realm_v1_storage_proto_depIdxs,
		MessageInfos:      file_proto_realm_v1_storage_proto_msgTypes,
	}.Build()
	File_proto_realm_v1_storage_proto = out.File
	file_proto_realm_v1_storage_proto_goTypes = nil
	file_proto_realm_v1_storage_proto_depIdxs = nil
}
