// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: realm/v1/token.proto

package realmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TokenPrefix   string                 `protobuf:"bytes,3,opt,name=token_prefix,json=tokenPrefix,proto3" json:"token_prefix,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	RateLimitRpm  int32                  `protobuf:"varint,5,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	LastUsedAt    *string                `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	ExpiresAt     *string                `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,8,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIToken) Reset() {
	*x = APIToken{}
	mi := &file_realm_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIToken) ProtoMessage() {}

func (x *APIToken) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIToken.ProtoReflect.Descriptor instead.
func (*APIToken) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *APIToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIToken) GetTokenPrefix() string {
	if x != nil {
		return x.TokenPrefix
	}
	return ""
}

func (x *APIToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *APIToken) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *APIToken) GetLastUsedAt() string {
	if x != nil && x.LastUsedAt != nil {
		return *x.LastUsedAt
	}
	return ""
}

func (x *APIToken) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

func (x *APIToken) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *APIToken) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_realm_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{1}
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*APIToken            `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_realm_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *ListTokensResponse) GetTokens() []*APIToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CreateTokenRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scopes           []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	RateLimitRpm     int32                  `protobuf:"varint,3,opt,name=rate_limit_rpm,json=rateLimitRpm,proto3" json:"rate_limit_rpm,omitempty"`
	ExpiresInSeconds *int64                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3,oneof" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_realm_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateTokenRequest) GetRateLimitRpm() int32 {
	if x != nil {
		return x.RateLimitRpm
	}
	return 0
}

func (x *CreateTokenRequest) GetExpiresInSeconds() int64 {
	if x != nil && x.ExpiresInSeconds != nil {
		return *x.ExpiresInSeconds
	}
	return 0
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *APIToken              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RawToken      string                 `protobuf:"bytes,2,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_realm_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTokenResponse) GetToken() *APIToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateTokenResponse) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_realm_v1_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_realm_v1_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_v1_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_realm_v1_token_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeTokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RevokeTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_realm_v1_token_proto protoreflect.FileDescriptor

const file_realm_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x14realm/v1/token.proto\x12\brealm.v1\"\xb8\x02\n" +
	"\bAPIToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ftoken_prefix\x18\x03 \x01(\tR\vtokenPrefix\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12$\n" +
	"\x0erate_limit_rpm\x18\x05 \x01(\x05R\frateLimitRpm\x12%\n" +
	"\flast_used_at\x18\x06 \x01(\tH\x00R\n" +
	"lastUsedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\a \x01(\tH\x01R\texpiresAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\b \x01(\bR\tisRevoked\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\x0f\n" +
	"\r_last_used_atB\r\n" +
	"\v_expires_at\"\x13\n" +
	"\x11ListTokensRequest\"@\n" +
	"\x12ListTokensResponse\x12*\n" +
	"\x06tokens\x18\x01 \x03(\v2\x12.realm.v1.APITokenR\x06tokens\"\xb0\x01\n" +
	"\x12CreateTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12$\n" +
	"\x0erate_limit_rpm\x18\x03 \x01(\x05R\frateLimitRpm\x121\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\x03H\x00R\x10expiresInSeconds\x88\x01\x01B\x15\n" +
	"\x13_expires_in_seconds\"\\\n" +
	"\x13CreateTokenResponse\x12(\n" +
	"\x05token\x18\x01 \x01(\v2\x12.realm.v1.APITokenR\x05token\x12\x1b\n" +
	"\traw_token\x18\x02 \x01(\tR\brawToken\"$\n" +
	"\x12RevokeTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13RevokeTokenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xef\x01\n" +
	"\fTokenService\x12G\n" +
	"\n" +
	"ListTokens\x12\x1b.realm.v1.ListTokensRequest\x1a\x1c.realm.v1.ListTokensResponse\x12J\n" +
	"\vCreateToken\x12\x1c.realm.v1.CreateTokenRequest\x1a\x1d.realm.v1.CreateTokenResponse\x12J\n" +
	"\vRevokeToken\x12\x1c.realm.v1.RevokeTokenRequest\x1a\x1d.realm.v1.RevokeTokenResponseB;Z9github.com/irvanmalik48/realm-api/pkg/pb/realm/v1;realmv1b\x06proto3"

var (
	file_realm_v1_token_proto_rawDescOnce sync.Once
	file_realm_v1_token_proto_rawDescData []byte
)

func file_realm_v1_token_proto_rawDescGZIP() []byte {
	file_realm_v1_token_proto_rawDescOnce.Do(func() {
		file_realm_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realm_v1_token_proto_rawDesc), len(file_realm_v1_token_proto_rawDesc)))
	})
	return file_realm_v1_token_proto_rawDescData
}

var file_realm_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_realm_v1_token_proto_goTypes = []any{
	(*APIToken)(nil),            // 0: realm.v1.APIToken
	(*ListTokensRequest)(nil),   // 1: realm.v1.ListTokensRequest
	(*ListTokensResponse)(nil),  // 2: realm.v1.ListTokensResponse
	(*CreateTokenRequest)(nil),  // 3: realm.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil), // 4: realm.v1.CreateTokenResponse
	(*RevokeTokenRequest)(nil),  // 5: realm.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil), // 6: realm.v1.RevokeTokenResponse
}
var file_realm_v1_token_proto_depIdxs = []int32{
	0, // 0: realm.v1.ListTokensResponse.tokens:type_name -> realm.v1.APIToken
	0, // 1: realm.v1.CreateTokenResponse.token:type_name -> realm.v1.APIToken
	1, // 2: realm.v1.TokenService.ListTokens:input_type -> realm.v1.ListTokensRequest
	3, // 3: realm.v1.TokenService.CreateToken:input_type -> realm.v1.CreateTokenRequest
	5, // 4: realm.v1.TokenService.RevokeToken:input_type -> realm.v1.RevokeTokenRequest
	2, // 5: realm.v1.TokenService.ListTokens:output_type -> realm.v1.ListTokensResponse
	4, // 6: realm.v1.TokenService.CreateToken:output_type -> realm.v1.CreateTokenResponse
	6, // 7: realm.v1.TokenService.RevokeToken:output_type -> realm.v1.RevokeTokenResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_realm_v1_token_proto_init() }
func file_realm_v1_token_proto_init() {
	if File_realm_v1_token_proto != nil {
		return
	}
	file_realm_v1_token_proto_msgTypes[0].OneofWrappers = []any{}
	file_realm_v1_token_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realm_v1_token_proto_rawDesc), len(file_realm_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realm_v1_token_proto_goTypes,
		DependencyIndexes: file_realm_v1_token_proto_depIdxs,
		MessageInfos:      file_realm_v1_token_proto_msgTypes,
	}.Build()
	File_realm_v1_token_proto = out.File
	file_realm_v1_token_proto_goTypes = nil
	file_realm_v1_token_proto_depIdxs = nil
}
